create table store_api.review
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_id bigint not null,
  description text not null,
  creation_date timestamp not null
);

alter table store_api.review add constraint fk_review_purchase foreign key (purchase_id) references purchase(id);
